name: CI Tests

on: push

jobs:
  node-test:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [9.x, 10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Node.js Test Suite
      run: |
        npm install
        npm test
