name: Image Scan

on:
  pull_request:
    branches:
      - master

jobs:
  anchore:

    runs-on: ubuntu-18.04

    steps:
      - name: Wait for image to be published
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: docker-publish
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Scan Image
        uses: anchore/scan-action@master
        with:
          image-reference: "pcic/climate-explorer-frontend:${{ github.event.pull_request.head.ref }}"
          fail-build: true
        if: steps.wait-for-build.outputs.conclusion == 'success'
